echo "Setting The Paths"
local_path="/mnt/c/Users/Andreu/Documents/GitHub/MLP_Project/Cluster/"
local_data_path="/mnt/c/Users/Andreu/Documents/GitHub/MLP_Project/data/"
remote_path="s2000253@mlp1:mlpractical/"
remote_data_path="s2000253@mlp1:mlpractical/data/"
